### PR TITLE
[JENKINS-46004] Bump jquery to align with other components

### PR DESCRIPTION
**Pull request by ghost**
@kohsuke 

https://issues.jenkins-ci.org/browse/JENKINS-46004

### CODE REVIEW

**Comment by recampbell** [comment]
I think we want @reviewbybees on this too, no?

**Comment by oleg-nenashev** [comment]
Yeah, otherwise nobody would notice it - 6 watchers in the repo

**Comment by ghost** [comment]
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

**Comment by oleg-nenashev** [comment]
@rysteboe Have you checked if JQuery 1.11.2 and 1.12.4 compatible with each other just in case?

**Comment by ghost** [comment]
Heh, whoops, good call Ryan.

Per the [upgrade guide](https://jqueryui.com/upgrade-guide/1.12/), there are some breaking API changes.  However, where possible, they've done some stuff to also import the 1.11 API's so that the upgrade can be done seamlessly.  

I did do some testing with plugins that depend on this and I didn't see any issues.  Most of the Googling that I did around 1.11.x -> 1.12.x breakages have been fixed as of 1.12.4.

**Comment by oleg-nenashev** [comment]
"Welcome to the Javascript world" :)

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
The compatibility topic needs more investigation, hence 🐛 for the current state

**Comment by kohsuke** [comment]
For me, this is OK as-is. jQuery not following semver is unfortunate but that's outside our control. Use of this in Jenkins requires caution.

**Review by kohsuke — APPROVED** [review]

**Comment by oleg-nenashev** [comment]
Existing usages of this lib still need to be investigated at least. If there are breakages, they need to be fixed by a coordinated update

**Comment by ghost** [comment]
@oleg-nenashev I have looked into the different uses of this library.  I do not see any problematic behavior based on the documented breaking change (only one) and internet searches indicate that the other backwards compatibility issues have been ironed out.  It's entirely possible that I'm missing something, but I don't believe that this will have ill effects.

**Comment by oleg-nenashev** [comment]
@rysteboe Could you please put the investigation results (dependent components) to https://issues.jenkins-ci.org/browse/JENKINS-46004 ? Just to have a track of what has been checked.

But generally I am fine with the YOLO mode after that

**Comment by ghost** [comment]
@oleg-nenashev added a comment to the ticket

**Review by oleg-nenashev — APPROVED** [review]
@rysteboe Thanks for that!

The test coverage looks good to me. We need to make sure that the changes are properly logged in JQuery Plugin Changelog, but probably we do not even need `compatibleSince` in this case.

🐝 and @reviewbybees done

**Comment by ghost** [comment]
@kohsuke, I think on you to merge?

**Pull request merged**
